name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get install -y libcunit1 libcunit1-dev
    - name: Build and test
      run: |
        make
        make test
